[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
all-features = true

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow = [
  { crate = "wise" },
  { crate = "core-foundation-sys@0.8.7", reason = "provides low-level API to CoreFoundation" },
  { crate = "accessibility-sys@0.1.3", reason = "provides low-level API to ApplicationServices accessibility" },
  { crate = "snafu@0.8.5", reason = "ergonomic error handling" },
  { crate = "snafu-derive@0.8.5", reason = "proc-macro support for snafu error handling" },
  { crate = "proc-macro2@1.0.94", reason = "required by snafu-derive and quote" },
  { crate = "quote@1.0.40", reason = "required by snafu-derive" },
  { crate = "syn@2.0.100", reason = "required by snafu-derive for parsing Rust code" },
  { crate = "heck@0.5.0", reason = "used by snafu-derive for case conversions" },
  { crate = "unicode-ident@1.0.18", reason = "dependency of proc-macro2 for identifiers" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-git = ["https://github.com/ethanuppal/core-foundation-rs"]


[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "GPL-3.0"]
confidence-threshold = 1.0
