name: CI

on:
  pull_request:
  push:
    branches:
      - rust

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1 # since we cache
  COLOG: 1

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
